// Code generated by mockery v2.7.4. DO NOT EDIT.

package app

import (
	repository "github.com/angeliski/git-fork/domain/repository"
	mock "github.com/stretchr/testify/mock"
)

// BusinessService is an autogenerated mock type for the BusinessService type
type BusinessService struct {
	mock.Mock
}

// Fork provides a mock function with given fields: model
func (_m *BusinessService) Fork(model repository.Model) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(repository.Model) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sync provides a mock function with given fields: model
func (_m *BusinessService) Sync(model repository.Model) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(repository.Model) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
